### ISSUE TITLE
private registry without official certificates

### ISSUE THREAD

**Issue by David9902** [confidential-containers/image-rs#132]
Hello, 
is it possible to use a local registry without official certificates (just HTTP)?
I used the option with the auth.json file as is was mentioned in a earlier thread. 
https://github.com/confidential-containers/image-rs/blob/main/docs/image_auth.md 

I added an insecure part as it would be done in docker for non-HTTPS registries:
```
{
    "auths": {
            "192.168.0.66:443": {
                    "auth": "QWxpY2U6cHN3ZAo="
            }
    },
   "insecure-registries" : ["192.168.0.66:443"]
 }
```
I am getting following error meaning that it did not recognize the "insecure-registries" part. 
  `Warning  Failed     6s               kubelet            Failed to pull image "192.168.0.66:443/nginx:1.22.0": rpc error: code = Unknown desc = failed to pull and unpack image "192.168.0.66:443/nginx:1.22.0": failed to resolve reference "192.168.0.66:443/nginx:1.22.0": failed to do request: Head "https://192.168.0.66:443/v2/nginx/manifests/1.22.0": http: server gave HTTP response to HTTPS client`

Or is there a way to get self-signed certificates into image-rs (like usually placed in /etc/ssl/certs/domain.crt)?

In case you want to reproduce: 
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  auth.json: |
    {
        "auths": {
                "192.168.0.66:443": {
                        "auth": "QWxpY2U6cHN3ZAo="
                }
        },
       "insecure-registries" : ["192.168.0.66:443"]
     }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
        - name: nginx
          image: 192.168.0.66:443/nginx:1.22.0
          volumeMounts:
            - name: config-volume
              mountPath: /run/image-security/
          ports:
            - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            name: auth-config
```
