### ISSUE TITLE
Ci: Need to involve tests in signature sub module

### ISSUE THREAD

**Issue by Xynnn007** [confidential-containers/image-rs#48]
In fact, every time the CI is triggered, tests in `signature` sub module are not performed.
It can be fixed by changing
```yaml
      - name: Run cargo test with root privilege
        run: |
          sudo -E PATH=$PATH -s cargo test
```
to
```yaml
      - name: Run cargo test with root privilege
        run: |
          sudo -E PATH=$PATH -s cargo test -p signature@0.1.0 -p image-rs
```
